name       : lightdm-gtk-greeter-settings
version    : 1.2.2
release    : 6
source     :
    - https://github.com/Xubuntu/lightdm-gtk-greeter-settings/releases/download/lightdm-gtk-greeter-settings-1.2.2/lightdm-gtk-greeter-settings-1.2.2.tar.gz : 4364d8b25b23d2ef4856d19724fd6c67de9a2d3c1b3833f7a5441145fd39dcb7
license    : GPL-3.0-or-later
component  : system.utils
summary    : Dialog for modifying the settings of lightdm-gtk-greeter
description: |
    Just a small dialog to make it easier for users to modify the settings of lightdm-gtk-greeter.
builddeps  :
    - python-distutils-extra
    - python-gobject-devel
rundeps    :
    - python-gobject
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-support-for-stateless-lightdm-gtk-greeter.patch
build      : |
    %python3_setup
install    : |
    %python3_install
