name       : lightdm-gtk-greeter-settings
version    : 1.2.1
release    : 3
source     :
    - https://launchpad.net/lightdm-gtk-greeter-settings/1.2/1.2.1/+download/lightdm-gtk-greeter-settings-1.2.1.tar.gz : ab91027b56ca0e0c98a38169acc453c08801bc4937dc1a53bd6e98b7aaceea96
license    : GPL-3.0
component  : system.utils
summary    : Dialog for modifying the settings of lightdm-gtk-greeter
description: |
    Just a small dialog to make it easier for users to modify the settings of lightdm-gtk-greeter.
builddeps  :
    - python-distutils-extra
    - python3-gobject-devel
rundeps    :
    - python3-gobject
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-support-for-stateless-lightdm-gtk-greeter.patch
build      : |
    %python3_setup
install    : |
    %python3_install
